source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'carrierwave'
gem 'mini_magick'
gem 'redis'
gem 'will_paginate'
gem 'friendly_id', '~> 5.1.0'

group :development, :test do
  gem 'spring'
  gem 'sqlite3'
  gem 'pry-rails'
  gem 'faker'
  gem 'rack-mini-profiler'
  gem 'web-console', '~> 2.0'
end
